{% set name = "ndcube" %}
{% set version = "1.4.1" %}
{% set sha256 = "73dc92ca348c5af628fc0d52e233e6f24aba8745953ceddbf6a0cf5618cec2f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --offline --no-git --single-version-externally-managed --record record.txt

requirements:
  build:
    - python >=3.6
    - setuptools
    - setuptools_scm

  run:
    - python >=3.6
    - astropy >=3.1
    - matplotlib-base >=2
    - sunpy >=1.0.3

test:
  requires:
    - pytest-astropy

  imports:
    - ndcube
    - ndcube.tests
    - ndcube.utils
    - ndcube.utils.tests

  commands:
    - pytest --pyargs ndcube

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: A base package for multi-dimensional contiguious and non-contiguious spatially aware arrays.
  license_family: BSD
  dev_url: https://github.com/sunpy/ndcube

extra:
  recipe-maintainers:
    - SolarDrew
    - Cadair
    - DanRyanIrish
