travis:
  secure:
    BINSTAR_TOKEN: XFabvoO9N/f6QyR36VZ1YFjI7fLPxKfx7rtv2VoPTBoIfXn0io7DH0h5qw6K5jBNB7m9uubYAfi7I8jV8L0JTK2PoMwuKuA5RJX17yxfcF9VDxc3gWralJeX/pY/ft/p4eUEEqdWk8QRe+bcZ67Wt2tDrMphsgIibJaOfuplx2PK/+JA0Pa+CTZS9v/9zsiJ1fA4Dzh/7G1n/aHs6wKXAw05k5MR3mtwm73/us9P6xQidEJlQv3mWqGTpAGsY7VBuUzKXQmy38vlLaiDREMrQxdvfoANiIm0y+m1B69Ko2UklB98HpDWAnbuUWnQP6XR8rk48dPdyBlxn9Ig1YHQ5PimNy0CgwD76zgyBb2APfIeTXqn+1rd6SRgkjxVweJGe4S9+vtrE+EGiToFwxdUCW3cQ8HM6rKU/TD3I6DBUWBtfTP2uupUhRXKKB3m2ZfW0teYZoYXzSFCeLbJcNFodTxFEdv+foUWfFUk9sKOQAF6vTdJBoUHDkZ8Castvr6KaUwc7/ikpNQ+r2Og4HZWabd42eDNehyjbKCNxrPk9Iy2tV5nEiZcrjfa6Eo6JMNknw4gLQ1ieGVo/6tA4T4UkU/5Bc1RFcDm+QTPOX7o2i6S+w9zqC+SNmVh01JQ6LuYEZKw3h1/0fwnvZDP4hwoQ1I+RFqUYKCy3MKEMgrEdRs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
